### ISSUE TITLE
Warn about missing space in `doubleprecision`, `enddo`, `endif` etc.

### ISSUE THREAD

**Issue by Beliavsky** [PlasmaFAIR/fortitude#178] opened 2024-12-02 22:43 UTC
I don't know what the precise terminology is, but Fortran allows some two-word keywords such as `double precision`, `end do`, `end if` to be written without the space as `doubleprecision`, `enddo`, `endif`. I think omitting the space makes the code less readable and that should be an option to warn about (and ideally fix) such usage.

**Comment by ZedThree** [comment] 2024-12-03 09:24
We agree! This is a duplicate of #66

**Closed by ZedThree** 2024-12-03 09:24 UTC
