### ISSUE TITLE
Per-line ignore

### ISSUE THREAD

**Issue by jwallwork23** [PlasmaFAIR/fortitude#209] opened 2024-12-09 10:08 UTC
Hi, thanks for creating Fortitude - I'm finding it really useful!

Would it be feasible to introduce per-line ignores? My use case is that I have a program that uses operator overloading and I'm not aware of a way to import the overloaded operators without using a bare `use` statement (no `only` specifications). So in this case I'd put a comment after the `use` statement telling Fortitude to ignore M011.

**Comment by ZedThree** [comment] 2024-12-09 11:03
Yep, this is very much in the plan! Exact form to be determined, but likely something like:

```f90
! allow(use-all)
use my_mod
```

Also, I think you should be able to write:

```f90
use my_mod, only: my_type, operator(+), operator(.eq.) ! etc
```

to import overloaded operators

**Comment by jwallwork23** [comment] 2024-12-09 11:05
Great! Thanks very much, I wasn't aware of that.

**Comment by LiamPattinson** [comment] 2024-12-10 12:15
Closing this as it's a duplicate of https://github.com/PlasmaFAIR/fortitude/issues/6, but don't worry, this is next-up on our priorities list!

**Comment by LiamPattinson** [comment] 2024-12-10 14:53
Actually, never mind, Issue https://github.com/PlasmaFAIR/fortitude/issues/6 rolls two independent issues into one, so I'm narrowing the scope of that one to just per-file ignores, and re-opening this. Sorry for the mess!

**Comment by LiamPattinson** [comment] 2024-12-10 15:00
We were having a chat about this earlier today, and the algorithm should look something like:

- Gather all rule violations for a file as usual
- Scan the AST for comments, find those that match the chosen syntax
- For each `allow` comment, find the immediate next sibling in the AST
- If the range of the violation intersects the comment sibling and the rule type matches the pattern, discard the violation

The neat thing about this method is that if you put the `allow` comment above a function or a module, it will apply to every line of code within!

**Closed** 2024-12-20 14:56 UTC
Labels: enhancement
